name: MongoDB Keep Alive

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  ping-mongodb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install mongoose and run keeep-aliv script
        working-directory: backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          npm install mongoose
          node keepAlive.js
